version: '3'

services:
  scimgateway:
    build: ./scimgateway
    ports:
      - "8880:8880"
    restart: always
    environment:
      loki-new-connector_BASIC_0_USERNAME: g
      loki-new-connector_BASIC_0_PASSWORD: v

    volumes:
      - data:/home/node/app/data
   
  
  
     

volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/qscim/data/oigit/data